### ISSUE TITLE
Error: More than one instance of bitcore found with different versions: v0.11.7 and v0.11.7

### ISSUE THREAD

**Issue by olalonde** [bitpay/bitcore#1188]
Getting this error:

```bash
/src/node_modules/bitcore-p2p/node_modules/bitcore/index.js:17
  throw new Error(message);
        ^
Error: More than one instance of bitcore found with different versions: v0.11.7 and v0.11.7. Make sure there are no version conflicts between package.json files of your dependencies. This could also happen when a package depends on a git repository.
    at Object.<anonymous> (/src/node_modules/bitcore-p2p/node_modules/bitcore/index.js:17:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/src/node_modules/bitcore-p2p/index.js:1:77)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

IMO, the current solution of checking for different require'd bitcore versions is really hacky and not idiomatic Node.js. The real solution would be to avoid relying on `instanceof`.

**Comment by braydonf** [comment]
This is likely caused by the scenario where two modules are both requiring bitcore:
`/node_modules/modulea/node_modules/bitcore`
`/node_modules/moduleb/node_modules/bitcore`

This can be solved by requiring bitcore in the main project, and the other two modules are not needed:
`/node_modules/bitcore/`.

There will still be issues with using two different versions of bitcore even if not using `instanceof`, that check is failing early to avoid other errors.

**Comment by olalonde** [comment]
This is causing the error:

```javascript
var bitcore = require('bitcore');
var Peer = require('bitcore-p2p').Peer;
```

How would I access `Peer` without requiring bitcore-p2p?

**Comment by olalonde** [comment]
Temporary workaround:

```javascript
var bitcore = require('bitcore');
delete global._bitcore;
var Peer = require('bitcore-p2p').Peer;
```

**Comment by braydonf** [comment]
Unless there are different versions that shouldn't raise an error. What versions of each are listed in `package.json`?

**Comment by olalonde** [comment]
Both same versions. Also tried to use `bitpay/bitcore` and `bitpay/bitcore-p2p`

**Comment by maraoz** [comment]
@olalonde weird. Can you show us your package.json? I'll try to reproduce your problem.
Is it possible that you're using a symbolic link for some dependency? (e.g.: you're using your local version of bitcore instead of downloading it via npm)

**Comment by Levino** [comment]
@olalonde Best workaround ever, thank you. @maraoz Please fix the include guards they really mess it up. It seems to be non standard. I include bitcore in dozens of places and why should I not? Every other package can handle it...

**Comment by maraoz** [comment]
@Levino for context on why that was added: https://github.com/bitpay/bitcore/issues/1164
I'm sorry it's working incorrectly, we should really fix this. If you have any extra information on how to reproduce this bug, please let me know. I haven't been able so far, and can't fix it :(

**Comment by olalonde** [comment]
The problem seems to be gone after a fresh npm install of both modules.

**Comment by joshuavial** [comment]
@maraoz the error is due to the order packages are installed. Try
```
npm i --save bitcore-explorers
npm i --save bitcore
echo "require('bitcore')\nrequire('bitcore-explorers')" > error.js
node error.js
```

installing bitcore before any extensions or at the same time `npm i --save bitcore-exceptions bitcore` won't produce the error

**Comment by braydonf** [comment]
@joshuavial The same scenario was mentioned on this PR related to peerDependencies: https://github.com/bitpay/bitcore-mnemonic/pull/26

**Comment by shea256** [comment]
@maraoz @olalonde what was the conclusion after all this? I'm still getting this error.

The quick hack with `delete global._bitcore;` works for me but it'd be nice to have an elegant permanent fix to this.

**Comment by braydonf** [comment]
Requiring "bitcore" in the top-level package should resolve the issue, more information is available here currently: https://github.com/bitpay/bitcore/issues/1328

**Comment by Levino** [comment]
@braydonf I think this issue needs to be reopened. I have never heard of a package that you are not allowed to require in a subpackage but only at the top. This is 90's style, if you ask me. What is npm require for then?

**Comment by shea256** [comment]
@Levino agreed.

And @braydonf, no that does not resolve the issue.

**Comment by braydonf** [comment]
@shea256 Even after fresh npm install?

**Comment by Levino** [comment]
@braydonf Can I do require('bitcore') in all files (or ten times in one file) in my project and in all files in my libraries in "node_modules"?

I cannot check the answer to your question yet. Maybe it was because of mixing old and new versions. Will come later when I have the time to check this.

**Comment by fanatid** [comment]
@Levino are you using `peerDependencies` for `bitcore` in libraries?
because with this, all works fine... example: [cc-scanner](https://github.com/chromaway/cc-scanner/blob/master/package.json#L53) uses `bitcore` and [coloredcoinjs-lib](https://github.com/fanatid/coloredcoinjs-lib/blob/master/package.json#L63) that have `bitcore` in `peerDependencies`
