### ISSUE TITLE
CORS Request failure on test-insight.bitpay.com

### ISSUE THREAD

**Issue by Christewart** [bitpay/bitcore#1352]
Hi everyone,

I've recently started receiving the following error when querying bitpay's insight node.

XMLHttpRequest cannot load https://test-insight.bitpay.com/api/addrs/utxo. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://test.extrapoint.io' is therefore not allowed access.
suredbits.wallet.js:203 Uncaught Error: CORS request rejected: https://test-insight.bitpay.com/api/addrs/utxo

This started happening on both my localhost and test server a couple of days ago. Before that I wasn't having any issues. Is there a simple way to fix this? Here is the code I am using to query the address

```javascript 

insight.getUnspentUtxos(address, function(err, utxos) {
    if (err) {
      throw err;
    } else {
      console.log(utxos);
      callBack(err,utxos);
    }
});

```

**Comment by braydonf** [comment]
This issue has been fixed with: https://github.com/bitpay/insight-api/pull/406

**Comment by zebpaykang** [comment]
I still get this issue in the playground.

**Comment by SurpriseMF3000** [comment]
Hello,
still facing this issue on Localhost.

`Error: CORS request rejected: https://test-insight.bitpay.com/api/addrs/utxo`
