### ISSUE TITLE
V8 can't handle 'generate' RPC command when running in 'regtest'

### ISSUE THREAD

**Issue by osagga** [bitpay/bitcore#1657]
After a clean install of `bitcore v8`, when running in `regtest`, sending a generate command
```
bitcoin-cli -datadir=full-nodes/bitcoin/regtest/ generate 101
```

causes the bitcore-node to behave in an undefined state. The log of the node is as follows:

```
info: Added block 1a4213ca8450217c3270925a9dc47650451d8c8ffe28ed5b3112fec2ce9843ab chain=BTC, network=regtest
info: Added block 43eab1f45bf71508c9dae0fde4e55b77ac00a81c2ed4bfdbd7c037267c3517ef chain=BTC, network=regtest
info: Added block 07886645493302d718cf3dd1e53e79c7e395cf83bb201aa28b5d011e73390af4 chain=BTC, network=regtest
info: Added block 179f07b3fb8a1a14e9496447be070d592a0ecd7d7b80cfd9a8ccbb6f7401d6d9 chain=BTC, network=regtest
info: Added block 464685059f702da9f3cc8f2756ebcba65216f0bab39abd2628fadb157a94476c chain=BTC, network=regtest
info: Added block 60e06e2535fc0b6ddac994e25f5d6dd075a53e945bc3c5b3432679e0815e0a24 chain=BTC, network=regtest
info: Added block 5d42b08a884d9d70847ac34e93e5f2285416992d28430caa7100d82d3e785f6e chain=BTC, network=regtest
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): reorg
info: Added block 44cb18980f357758d9e1b74fad8579749758bdf67ee4012302d0d1e2f10ce373 chain=BTC, network=regtest
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): reorg
info: Added block 3cec06c47ce039dafb89ae3c1c1563cfd06f2119fd318dd34cc0a710e2ef5310 chain=BTC, network=regtest
info: Added block 5ca802a6f4194397ce2cd4ac582caa5814d2d1d5cc8ee30a3a7f0b637b8fe6f0 chain=BTC, network=regtest
info: Added block 374ee2e1b7195a4dd9066978aa8b3668d57c54868a888fe537ac268b8fdc97e9 chain=BTC, network=regtest
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 11): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 17): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 19): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 21): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 23): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 25): reorg
(node:23459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 27): reorg
info: Added block 58c6bf783d4fa045e23b66f5472039e11f46ea744f66d0c1a2b064d7a27e14ff chain=BTC, network=regtest
info: Added block 6a6f31bad2d6c5432ca925e1d187d064e22a3ecba5db7c3860ae510a629d035a chain=BTC, network=regtest
```

The node doesn't crash, but it runs in an undefined state where all blocks have a height of `1` or some weird value

```
$ curl -s localhost:3000/api/BTC/regtest/block | python -m json.tool
[
    {
        "bits": 545259519,
        "chain": "BTC",
        "hash": "39f808449062a5c36bd4b7960748cfa941f99a060dc9a95c267bb856215eaed9",
        "height": 1,
        "merkleRoot": "ece33d615b14d5fbf92611cd5bd14cab366cde81bc545b1d24fc46cef21d536e",
        "network": "regtest",
        "nonce": 0,
        "previousBlockHash": "60a23782bcca01c3edafd431f13c6041207e4358b814244c6ca836ca5ed51b88",
        "reward": 5000000000,
        "size": 227,
        "time": "2018-08-03T13:15:47.000Z",
        "timeNormalized": "2018-08-03T13:15:47.000Z",
        "transactionCount": 1,
        "version": 536870912
    },
    {
        "bits": 545259519,
        "chain": "BTC",
        "hash": "546b235fabbd3789077773acb72cbb2fb4fce341bbbf9f6c751cef64df2ab09d",
        "height": 1,
        "merkleRoot": "5a878a8d30507102fb888ac75c01305c7a7f1568bfdae1d2909fac63eb8e78f9",
        "network": "regtest",
        "nonce": 2,
        "previousBlockHash": "7c6c9654141c312bd9a98e60d751e5e340fea70eee559423728a1273eb785163",
        "reward": 5000000000,
        "size": 227,
        "time": "2018-08-03T13:15:48.000Z",
        "timeNormalized": "2018-08-03T13:15:48.000Z",
        "transactionCount": 1,
        "version": 536870912
    }
]
```

For some reason `reorg` is triggered when it shouldn't. The only alternative now is to generate `1` block at a time.

**Comment by micahriggan** [comment]
Ah yes, this one happens to me as well. I think it's something with bitcoreP2P

I was researching this for a little once
I believe bitcorep2p receives all 100 blocks at once, which then triggers the on('peerblock') 100 times in bitcore-node/p2p

It causes the addBlock function to set the height to 1, because it can't find the previous block, because  all 100 were triggered at once, so you get a bit of a race.

We would need to trigger the on('peerblock') event in bitcore-p2p in order, synchronously

**Comment by osagga** [comment]
Yeah that's exactly the fix I was thinking about, a queue might do.

**Comment by osagga** [comment]
It's fixed now, it seems. 

But the logging is a bit weird 
```
info: API server started on port 3000
info: Connected to peer 127.0.0.1 chain=BTC, network=regtest
info: Connected to peer 127.0.0.1 chain=BCH, network=regtest
info: Connected to peer 127.0.0.1 chain=LTC, network=regtest
info: Syncing 0 blocks for BTC regtest
info: BTC:regtest up to date.
info: Syncing 0 blocks for BCH regtest
info: BCH:regtest up to date.
info: Syncing 0 blocks for LTC regtest
info: LTC:regtest up to date.
info: Resetting tip to 5b42dec87077896bf9dffd2efe49431cf5811fda414a514273242ab8dcd68af7 chain=BTC, network=regtest
info: Resetting tip to 7c8116492833b68b6920d6029c7a9e5c0d0b8874aae75fa20ad5d49b764ba339 chain=BTC, network=regtest
info: Added block 1a2826437aed0663dc529d147b75f7e44379eea8c605ecd974302aeda9ec7c86 chain=BTC, network=regtest
info: Resetting tip to 1b6073b819962c769ce761bb8e91e1fbf5cb722455bbbcd1beb5704530002a66 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
info: Resetting tip to 52ddc6c544edd04d1dacd5d9caf13370b2c35b42700a2e054132a3cabb419db5 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
error: Error syncing BTC regtest reorg
info: Syncing 29 blocks for BTC regtest
error: Error syncing BTC regtest reorg
info: Syncing 35 blocks for BTC regtest
info: Syncing 35 blocks for BTC regtest
info: Syncing 35 blocks for BTC regtest
info: Sync progress 99.032% chain=BTC, network=regtest, height=307
info: Sync progress 99.032% chain=BTC, network=regtest, height=307
info: Sync progress 99.032% chain=BTC, network=regtest, height=307
info: Sync progress 99.032% chain=BTC, network=regtest, height=307
info: Sync progress 99.677% chain=BTC, network=regtest, height=309
info: Sync progress 99.677% chain=BTC, network=regtest, height=309
info: Sync progress 99.677% chain=BTC, network=regtest, height=309
info: Sync progress 99.677% chain=BTC, network=regtest, height=309
info: Sync progress 100.323% chain=BTC, network=regtest, height=311
info: Sync progress 100.323% chain=BTC, network=regtest, height=311
info: Sync progress 100.323% chain=BTC, network=regtest, height=311
info: Sync progress 100.323% chain=BTC, network=regtest, height=311
info: Sync progress 101.290% chain=BTC, network=regtest, height=314
```

since a `reorg` event is still triggered and it gets handled as an error here
https://github.com/bitpay/bitcore/blob/a22d1b641dfc2330ad865cc5e79e46384eeafd14/packages/bitcore-node/src/services/p2p.ts#L104
or here (maybe both)
https://github.com/bitpay/bitcore/blob/a22d1b641dfc2330ad865cc5e79e46384eeafd14/packages/bitcore-node/src/services/p2p.ts#L291

Also the sync progress is miscalculated here
https://github.com/bitpay/bitcore/blob/a22d1b641dfc2330ad865cc5e79e46384eeafd14/packages/bitcore-node/src/services/p2p.ts#L279-L288

I'll keep this open until I fully confirm it's working, and the logging is better. Thanks again.

**Comment by micahriggan** [comment]
So the underlying bitcorep2p problem is still probably present, but the error handling restarts sync which should resolve itself. Still need to fix the underlying bitcore-p2p thing, but I won't be able to get to that for a bit

**Comment by micahriggan** [comment]
Mind logging out what this.getBestPoolHeight() is when this type of event occurs?

I'd bet it's not the correct height, which is causing the percentage to go over 100%

Very likely the code that updates the pool height in bitcore-p2p needs some help handling multiple blocks coming in at the same time.

**Comment by osagga** [comment]
Hey, so this is what I have:

I started a clean node with a clean mongoDb, and then I generated `101` blocks
```
$ ./full-nodes/bitcoin/bin/bitcoin-cli -datadir=full-nodes/bitcoin/regtest/ -regtest generate 101
```

I added a logging message here:

```
if (Date.now() - lastLog > 100) {
            logger.info(`Current BestPoolHeight is ${this.getBestPoolHeight()}`);
            logger.info(`Sync progress ${((100 * currentHeight) / this.getBestPoolHeight()).toFixed(3)}%`, {
              chain,
              network,
              height: currentHeight
            });
            lastLog = Date.now();
          }
```

And this is the output:
```
info: API server started on port 3000
info: Connected to peer 127.0.0.1 chain=BTC, network=regtest
info: Connected to peer 127.0.0.1 chain=BCH, network=regtest
info: Connected to peer 127.0.0.1 chain=LTC, network=regtest
info: Syncing 0 blocks for BCH regtest
info: BCH:regtest up to date.
info: Syncing 0 blocks for BTC regtest
info: BTC:regtest up to date.
info: Syncing 0 blocks for LTC regtest
info: LTC:regtest up to date.
info: Added block 39c1d5d73aeae3863ac5579a8cfcc23e5698dab2e85d0a1c68305764525a4e0f chain=BTC, network=regtest
info: Resetting tip to 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
info: Syncing 19 blocks for BTC regtest
info: Resetting tip to 5c5be96626014b2fb6e1c148fa7e10438018bd6f73c2cf113ffce05d87ecfc34 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
info: Syncing 25 blocks for BTC regtest
info: Current BestPoolHeight is 0
info: Sync progress Infinity% chain=BTC, network=regtest, height=1
info: Current BestPoolHeight is 0
info: Sync progress Infinity% chain=BTC, network=regtest, height=7
info: Current BestPoolHeight is 0
info: Sync progress Infinity% chain=BTC, network=regtest, height=15
info: Current BestPoolHeight is 0
info: Sync progress Infinity% chain=BTC, network=regtest, height=23
info: Syncing 76 blocks for BTC regtest
info: Current BestPoolHeight is 0
info: Sync progress Infinity% chain=BTC, network=regtest, height=26
info: Current BestPoolHeight is 0
info: Sync progress Infinity% chain=BTC, network=regtest, height=36
info: Current BestPoolHeight is 0
info: Sync progress Infinity% chain=BTC, network=regtest, height=44
info: Current BestPoolHeight is 0
info: Sync progress Infinity% chain=BTC, network=regtest, height=55
info: Current BestPoolHeight is 0
info: Sync progress Infinity% chain=BTC, network=regtest, height=67
info: Current BestPoolHeight is 0
info: Sync progress Infinity% chain=BTC, network=regtest, height=78
info: Current BestPoolHeight is 0
info: Sync progress Infinity% chain=BTC, network=regtest, height=91
info: Syncing 0 blocks for BTC regtest
info: BTC:regtest up to date.
```

As you can tell, it stays at `0`, which is really weird since it means that `peer.bestHeight` is `0`
https://github.com/bitpay/bitcore/blob/242c2ab787daedaacb2b1cc4a8961b14c529c572/packages/bitcore-node/src/services/p2p.ts#L198-L206

I think you're right, it's an underlying bitcorep2p problem. What do you think?

**Comment by micahriggan** [comment]
I dug into this a bit on Friday. The bestPoolHeight number comes from bitcoreP2P when you send the "version" message, a peer responds with it's version, and it's best height. But, once you get a peer's version, it won't respond to a "version" message again while you're connected. So we can't rely on that number updating

**Comment by osagga** [comment]
As of the recent merge commit 242c2ab787daedaacb2b1cc4a8961b14c529c572, the logging message with the syncing persentage was removed, so the log is cleaner now. But the preentage was really helpful in showing progress, I'm not really sure if it'll be back.

Here's the log after the updates, I ran the node then generated `101` blocks for each blockchain (BTC, BCH, LTC). You can still see some error messages regarding the reorg, also some info statments report syncing `0` block while actually syncing more than that.

 (sorry for the long log)
```
$ npm run node
info: API server started on port 3000
info: Connected to peer 127.0.0.1 chain=BCH, network=regtest
info: Connected to peer 127.0.0.1 chain=LTC, network=regtest
info: Connected to peer 127.0.0.1 chain=BTC, network=regtest
info: Syncing 0 blocks for BTC regtest
info: BTC:regtest up to date.
info: Syncing 0 blocks for BCH regtest
info: BCH:regtest up to date.
info: Syncing 0 blocks for LTC regtest
info: LTC:regtest up to date.
info: Added block 6613260e5b816a9a321c13b9316b0313f2965a9de2314fe19f4d9e4047eb5d6f chain=BTC, network=regtest
info: Added block 688aef0fdfbb27bfcb40a847f15faa13fb23910b064bdaad658541238442ad9f chain=BTC, network=regtest
info: Resetting tip to 688aef0fdfbb27bfcb40a847f15faa13fb23910b064bdaad658541238442ad9f chain=BTC, network=regtest
info: Resetting tip to 688aef0fdfbb27bfcb40a847f15faa13fb23910b064bdaad658541238442ad9f chain=BTC, network=regtest
info: Resetting tip to 688aef0fdfbb27bfcb40a847f15faa13fb23910b064bdaad658541238442ad9f chain=BTC, network=regtest
info: Resetting tip to 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206 chain=BTC, network=regtest
info: Added block 1f7edf2aba50ef85709d80aa4b32d1fe55c54a9e8838a53e6822d6153706da71 chain=BTC, network=regtest
info: Added block 63f54653ef7e44cf93f5b9759d091524fd7998025cc2a9359c4349a7e2801c71 chain=BTC, network=regtest
info: Added block 348df0c55a8cd6dedf70cb7e152d060e8ce5ec25fb1ee086e7563d5c4db647f0 chain=BTC, network=regtest
info: Added block 22c31a24d83aa687007fddcf4521ae4d745c7580442f26ad4ddfb6c393b263e1 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
error: Error syncing BTC regtest reorg
error: Error syncing BTC regtest reorg
info: Syncing 43 blocks for BTC regtest
info: Syncing 43 blocks for BTC regtest
info: Syncing 43 blocks for BTC regtest
error: Error syncing BTC regtest reorg
info: Resetting tip to 08d475470647139afe983ab8021141068d3c8393a63cd1a75ac57140cedc5b49 chain=BTC, network=regtest
info: Resetting tip to 08d475470647139afe983ab8021141068d3c8393a63cd1a75ac57140cedc5b49 chain=BTC, network=regtest
info: Resetting tip to 08d475470647139afe983ab8021141068d3c8393a63cd1a75ac57140cedc5b49 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
error: Error syncing BTC regtest reorg
error: Error syncing BTC regtest reorg
info: Syncing 26 blocks for BTC regtest
info: Syncing 32 blocks for BTC regtest
info: Syncing 32 blocks for BTC regtest
info: Syncing 32 blocks for BTC regtest
info: Resetting tip to 66be59b85e73b8974a1dec15b8f867de801ea28afb52211a1426ebf19c4d9499 chain=BTC, network=regtest
info: Resetting tip to 66be59b85e73b8974a1dec15b8f867de801ea28afb52211a1426ebf19c4d9499 chain=BTC, network=regtest
info: Resetting tip to 66be59b85e73b8974a1dec15b8f867de801ea28afb52211a1426ebf19c4d9499 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
error: Error syncing BTC regtest reorg
error: Error syncing BTC regtest reorg
info: Syncing 56 blocks for BTC regtest
info: Syncing 56 blocks for BTC regtest
info: Syncing 56 blocks for BTC regtest
info: Sync  chain=BTC, network=regtest, height=2
info: Resetting tip to 6852d63166e5ddf9dee67ba6bd035397c0258da10e1a02d6d0891926b89da8c5 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=2
info: Sync  chain=BTC, network=regtest, height=2
info: Sync  chain=BTC, network=regtest, height=2
info: Syncing 91 blocks for BTC regtest
info: Sync  chain=BTC, network=regtest, height=1
info: Resetting tip to 08d475470647139afe983ab8021141068d3c8393a63cd1a75ac57140cedc5b49 chain=BTC, network=regtest
info: Sync  chain=BTC, network=regtest, height=4
info: Sync  chain=BTC, network=regtest, height=4
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=4
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=BTC, network=regtest, height=1
info: Resetting tip to 120a8b19d5880d1535101814c71b45676dd5a47931d1bae8f24b2f5d94bb5d21 chain=BTC, network=regtest
info: Sync  chain=BTC, network=regtest, height=6
info: Sync  chain=BTC, network=regtest, height=6
info: Added block 5a7aea54544be3926640bdd487237cca5926399d8436b7fa4b58d3220b520bde chain=BCH, network=regtest
info: Resetting tip to 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206 chain=BCH, network=regtest
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=6
error: Error syncing BCH regtest reorg
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=BTC, network=regtest, height=7
info: Sync  chain=BTC, network=regtest, height=7
info: Resetting tip to 4eb92c39fdfec0458b3301aa5dd77115cde56e5f8f4759d1e263f18d10202349 chain=BTC, network=regtest
info: Added block 418d6318adc969d4a0e6aae5e8d8c65ef17b13745814f73a33c389cdea85f41b chain=LTC, network=regtest
info: Syncing 101 blocks for BCH regtest
info: Sync  chain=BTC, network=regtest, height=7
error: Error syncing BTC regtest reorg
info: Resetting tip to 530827f38f93b43ed12af0b3ad25a288dc02ed74d6d7857862df51fc56c416f9 chain=LTC, network=regtest
info: Added block 9b55489116a5463a8083ac46050d355ec941863f14b28c292da31cb3244b0d7e chain=LTC, network=regtest
error: Error syncing LTC regtest reorg
info: Syncing 101 blocks for BTC regtest
info: Resetting tip to 6cb135d885b30eff74024138f95eb5fd012893b8f569ab60242062559b3d28d1 chain=BTC, network=regtest
info: Sync  chain=BCH, network=regtest, height=1
info: Syncing 39 blocks for LTC regtest
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=9
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=BTC, network=regtest, height=9
info: Resetting tip to 043e9669dab168030396eb606bcfb8825d8fb65175e5e35bb5fa14a7e129bef9 chain=BTC, network=regtest
info: Sync  chain=BTC, network=regtest, height=9
info: Sync  chain=LTC, network=regtest, height=1
error: Error syncing BTC regtest reorg
info: Syncing 101 blocks for BTC regtest
info: Resetting tip to 16a6a949ae60362fbaff3ecaf07a255ec37a0256484485c9e219cad2d18e58e2 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
info: Sync  chain=BCH, network=regtest, height=3
info: Sync  chain=BTC, network=regtest, height=11
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=BTC, network=regtest, height=11
info: Sync  chain=LTC, network=regtest, height=2
info: Resetting tip to 2db2879fa77a511bca78293822d0fe19281dd913f3cd08f3d6a3628615b10a40 chain=BTC, network=regtest
info: Sync  chain=BTC, network=regtest, height=11
error: Error syncing BTC regtest reorg
info: Sync  chain=BCH, network=regtest, height=4
info: Syncing 101 blocks for BTC regtest
info: Resetting tip to 2d62dad149093e94b520258bdd738efef54e2b3e86d588282e0e2092c9f1f6d5 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=13
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=BTC, network=regtest, height=13
info: Sync  chain=BTC, network=regtest, height=13
info: Resetting tip to 3375a85dbaacca3a28bf0e49d920bc280f8b562538000080a77e4b66adc4dcce chain=BTC, network=regtest
info: Sync  chain=LTC, network=regtest, height=4
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=14
info: Sync  chain=BCH, network=regtest, height=6
info: Sync  chain=BTC, network=regtest, height=14
info: Syncing 101 blocks for BTC regtest
info: Resetting tip to 50ca97aa3563b77b30f7538bd6e70fcc26fb3b5920d0b066a423befce4de6d29 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=15
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=LTC, network=regtest, height=6
info: Resetting tip to 6c475b4e7e683bf9c7f2965b07b12f09f377c8d796f6ceaa1bca058a0107273a chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
info: Sync  chain=BCH, network=regtest, height=8
info: Sync  chain=BTC, network=regtest, height=16
info: Sync  chain=BTC, network=regtest, height=16
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=BTC, network=regtest, height=17
info: Sync  chain=LTC, network=regtest, height=8
info: Sync  chain=BTC, network=regtest, height=1
info: Resetting tip to 213bd8399f379281124ea09c99c3c01bc4298d5f7bf77b0d2096dfe8d81ef856 chain=BTC, network=regtest
info: Sync  chain=BTC, network=regtest, height=18
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=18
info: Sync  chain=BCH, network=regtest, height=10
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=BTC, network=regtest, height=19
info: Sync  chain=BTC, network=regtest, height=1
info: Sync  chain=LTC, network=regtest, height=10
info: Resetting tip to 6e858865cb6d50b7047dd88ed5c31841baadc88bdee52c27b7a3336cd8dafa79 chain=BTC, network=regtest
info: Sync  chain=BTC, network=regtest, height=20
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=20
info: Sync  chain=BCH, network=regtest, height=12
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=BTC, network=regtest, height=21
info: Sync  chain=BTC, network=regtest, height=1
info: Sync  chain=BCH, network=regtest, height=13
info: Resetting tip to 52d07247c597163d4f4ddd34a7e709e541a811c1fa6f6745e9c2137641dc12d1 chain=BTC, network=regtest
info: Sync  chain=LTC, network=regtest, height=12
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=22
info: Sync  chain=BTC, network=regtest, height=22
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=BTC, network=regtest, height=23
info: Sync  chain=BTC, network=regtest, height=1
info: Resetting tip to 73078d8745ff8cfb4407a617c956de47f4bdec86a6cd47c87544cbc9df01c9a2 chain=BTC, network=regtest
info: Sync  chain=BCH, network=regtest, height=15
info: Sync  chain=LTC, network=regtest, height=14
info: Sync  chain=BTC, network=regtest, height=24
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=24
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=BTC, network=regtest, height=25
info: Sync  chain=LTC, network=regtest, height=15
info: Sync  chain=BTC, network=regtest, height=25
info: Sync  chain=BTC, network=regtest, height=25
info: Sync  chain=BTC, network=regtest, height=1
info: Resetting tip to 73de6db24bd99d788b3e64010396c8e29d7a319c6c5bdeec17801264a91e59fe chain=BTC, network=regtest
info: Sync  chain=BCH, network=regtest, height=17
error: Error syncing BTC regtest reorg
info: Syncing 101 blocks for BTC regtest
info: Resetting tip to 27f74fecfd548860d98aa0462f4b029a65f58dc96aeb2a6dc8dc423072a6bc92 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=27
info: Sync  chain=BTC, network=regtest, height=27
info: Sync  chain=LTC, network=regtest, height=17
info: Sync  chain=BTC, network=regtest, height=27
info: Syncing 101 blocks for BTC regtest
info: Resetting tip to 2cb8d29864f1cecf01a4d132abbdd4cd219c6319059c39fcd1fa44f1c3724d2b chain=BTC, network=regtest
info: Sync  chain=BCH, network=regtest, height=19
error: Error syncing BTC regtest reorg
info: Syncing 101 blocks for BTC regtest
info: Resetting tip to 2def886fa9268a391520c2b48bac43a842c9d447a6edb83146048d988d25804f chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=29
info: Sync  chain=BTC, network=regtest, height=29
info: Sync  chain=LTC, network=regtest, height=19
info: Sync  chain=BTC, network=regtest, height=29
info: Syncing 101 blocks for BTC regtest
info: Resetting tip to 1f95e093024e958d001789b77451cf6d5ef7659b39bbfdc60543c153c2859dc4 chain=BTC, network=regtest
info: Sync  chain=BCH, network=regtest, height=21
error: Error syncing BTC regtest reorg
info: Syncing 101 blocks for BTC regtest
info: Resetting tip to 4829e13ee2cee00fee03604826aea749b790c1d898f90c1c485ac037d6ec2174 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=31
info: Sync  chain=BTC, network=regtest, height=31
info: Sync  chain=LTC, network=regtest, height=21
info: Sync  chain=BTC, network=regtest, height=31
info: Syncing 101 blocks for BTC regtest
info: Resetting tip to 76247266e391f6bf72c589bd4579bbb894b3a29a006fb6db7a5685e895e03c22 chain=BTC, network=regtest
info: Sync  chain=BCH, network=regtest, height=23
error: Error syncing BTC regtest reorg
info: Syncing 101 blocks for BTC regtest
info: Resetting tip to 2cd38c0bec088c807d3af8048dd6c7d2bed6a96802d75109413517f27564b60b chain=BTC, network=regtest
info: Sync  chain=BTC, network=regtest, height=33
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=33
info: Sync  chain=LTC, network=regtest, height=23
info: Sync  chain=BTC, network=regtest, height=33
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=BCH, network=regtest, height=25
info: Sync  chain=BTC, network=regtest, height=1
info: Resetting tip to 4c2399f1429771348f998ce8639d94783359dd6e0328bbc650855abf35e6b88c chain=BTC, network=regtest
info: Sync  chain=BTC, network=regtest, height=35
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=35
info: Sync  chain=LTC, network=regtest, height=25
info: Sync  chain=BTC, network=regtest, height=35
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=BCH, network=regtest, height=27
info: Sync  chain=BTC, network=regtest, height=1
info: Resetting tip to 08dc90c5729f85de80b41bf7d9373b0c05bf174f73879d2a41b2c78cf42dcddd chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=37
info: Sync  chain=BTC, network=regtest, height=37
info: Sync  chain=BTC, network=regtest, height=37
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=LTC, network=regtest, height=27
info: Sync  chain=BCH, network=regtest, height=29
info: Sync  chain=BTC, network=regtest, height=1
info: Resetting tip to 4a7864525c92b0e805232c5641899febd09b6c59167da2ff3a26071688a835c0 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=39
info: Sync  chain=BTC, network=regtest, height=39
info: Sync  chain=BTC, network=regtest, height=39
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=LTC, network=regtest, height=29
info: Sync  chain=BCH, network=regtest, height=31
info: Sync  chain=BTC, network=regtest, height=1
info: Resetting tip to 254766ea41faaf7c4200b1feeef6e201b554f443b3d1820336c5d4d0411dd8ac chain=BTC, network=regtest
info: Sync  chain=BTC, network=regtest, height=41
info: Sync  chain=BTC, network=regtest, height=41
info: Sync  chain=BTC, network=regtest, height=41
error: Error syncing BTC regtest reorg
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=LTC, network=regtest, height=31
info: Sync  chain=BCH, network=regtest, height=33
info: Sync  chain=BTC, network=regtest, height=1
info: Resetting tip to 64f2a8fbf69982442a62949f4f2f40e8846bfe756a666fad0b5858062ec23fc9 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=43
info: Sync  chain=BTC, network=regtest, height=43
info: Sync  chain=BTC, network=regtest, height=43
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=LTC, network=regtest, height=33
info: Sync  chain=BTC, network=regtest, height=1
info: Sync  chain=BCH, network=regtest, height=35
info: Resetting tip to 6690072cac37dd7987e904c47ef1d387e8a63c0204c7e124ceb35404c2bead87 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=45
info: Sync  chain=BTC, network=regtest, height=45
info: Sync  chain=BTC, network=regtest, height=45
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=LTC, network=regtest, height=35
info: Sync  chain=BTC, network=regtest, height=1
info: Resetting tip to 69831319d9fd10d5bf065edc9b6c734df79eadca4d85c1459eb691e26240b0be chain=BTC, network=regtest
info: Sync  chain=BCH, network=regtest, height=37
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=47
info: Sync  chain=BTC, network=regtest, height=47
info: Sync  chain=BTC, network=regtest, height=47
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=LTC, network=regtest, height=37
info: Sync  chain=BTC, network=regtest, height=1
info: Resetting tip to 0079297c99f8b8834e704476aac2aee6ab2f84aa36a7b08e83ad43f933faf91e chain=BTC, network=regtest
info: Sync  chain=BCH, network=regtest, height=39
info: Sync  chain=BTC, network=regtest, height=49
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=49
info: Sync  chain=BTC, network=regtest, height=49
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=LTC, network=regtest, height=39
info: Syncing 62 blocks for LTC regtest
info: Sync  chain=BTC, network=regtest, height=1
info: Resetting tip to 3729f5c71c2b75a4b2e3500e4f26798a6bf706c61d7dd2406842709c910872b8 chain=BTC, network=regtest
info: Sync  chain=BTC, network=regtest, height=51
info: Sync  chain=BCH, network=regtest, height=41
info: Sync  chain=BTC, network=regtest, height=51
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=51
info: Sync  chain=LTC, network=regtest, height=40
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=BTC, network=regtest, height=1
info: Resetting tip to 0dea3bb6bf0082ea9779820aaab639ba0c470b8bcd7639ada3ace42b0f7f732d chain=BTC, network=regtest
info: Sync  chain=BTC, network=regtest, height=53
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=53
info: Sync  chain=BTC, network=regtest, height=53
info: Sync  chain=BCH, network=regtest, height=43
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=LTC, network=regtest, height=42
info: Sync  chain=BTC, network=regtest, height=1
info: Resetting tip to 004179d8b2b80327f8e20e3806f1510542344cc4ca342264d5d8848cf66b65fc chain=BTC, network=regtest
info: Sync  chain=BTC, network=regtest, height=55
info: Sync  chain=BTC, network=regtest, height=55
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=55
info: Sync  chain=BCH, network=regtest, height=45
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=LTC, network=regtest, height=44
info: Sync  chain=BTC, network=regtest, height=1
info: Resetting tip to 0c20cc3204d3eae4494ce06913698e7c3e5a4a57d62b279e7cf6e1e0e4fa52be chain=BTC, network=regtest
info: Sync  chain=BTC, network=regtest, height=57
info: Sync  chain=BTC, network=regtest, height=57
error: Error syncing BTC regtest reorg
info: Syncing 101 blocks for BTC regtest
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=BTC, network=regtest, height=57
info: Sync  chain=BCH, network=regtest, height=47
info: Syncing 101 blocks for BTC regtest
info: Syncing 101 blocks for BTC regtest
info: Sync  chain=LTC, network=regtest, height=46
info: Sync  chain=BTC, network=regtest, height=1
info: Sync  chain=BTC, network=regtest, height=1
info: Sync  chain=BTC, network=regtest, height=1
info: Sync  chain=BTC, network=regtest, height=1
info: Sync  chain=BCH, network=regtest, height=49
info: Sync  chain=LTC, network=regtest, height=48
info: Sync  chain=BTC, network=regtest, height=3
info: Sync  chain=BTC, network=regtest, height=3
info: Sync  chain=BTC, network=regtest, height=3
info: Sync  chain=BTC, network=regtest, height=3
info: Sync  chain=BCH, network=regtest, height=51
info: Sync  chain=LTC, network=regtest, height=50
info: Sync  chain=BTC, network=regtest, height=5
info: Sync  chain=BTC, network=regtest, height=5
info: Sync  chain=BTC, network=regtest, height=5
info: Sync  chain=BTC, network=regtest, height=5
info: Sync  chain=BCH, network=regtest, height=53
info: Sync  chain=LTC, network=regtest, height=52
info: Sync  chain=BTC, network=regtest, height=7
info: Sync  chain=BTC, network=regtest, height=7
info: Sync  chain=BTC, network=regtest, height=7
info: Sync  chain=BTC, network=regtest, height=7
info: Sync  chain=BCH, network=regtest, height=55
info: Sync  chain=LTC, network=regtest, height=54
info: Sync  chain=BTC, network=regtest, height=9
info: Sync  chain=BTC, network=regtest, height=9
info: Sync  chain=BTC, network=regtest, height=9
info: Sync  chain=BTC, network=regtest, height=9
info: Sync  chain=BCH, network=regtest, height=57
info: Sync  chain=BTC, network=regtest, height=10
info: Sync  chain=LTC, network=regtest, height=56
info: Sync  chain=BTC, network=regtest, height=11
info: Sync  chain=BTC, network=regtest, height=11
info: Sync  chain=BTC, network=regtest, height=11
info: Sync  chain=BCH, network=regtest, height=59
info: Sync  chain=BTC, network=regtest, height=12
info: Sync  chain=LTC, network=regtest, height=58
info: Sync  chain=BTC, network=regtest, height=13
info: Sync  chain=BTC, network=regtest, height=13
info: Sync  chain=BTC, network=regtest, height=13
info: Sync  chain=BCH, network=regtest, height=61
info: Sync  chain=BTC, network=regtest, height=14
info: Sync  chain=LTC, network=regtest, height=60
info: Sync  chain=BTC, network=regtest, height=15
info: Sync  chain=BTC, network=regtest, height=15
info: Sync  chain=BTC, network=regtest, height=15
info: Sync  chain=BCH, network=regtest, height=63
info: Sync  chain=BTC, network=regtest, height=16
info: Sync  chain=LTC, network=regtest, height=62
info: Sync  chain=BTC, network=regtest, height=17
info: Sync  chain=BTC, network=regtest, height=17
info: Sync  chain=BTC, network=regtest, height=17
info: Resetting tip to 26c925fdc060cf5549579ee69022bafb408d1fe87fc86b5ac46a1f29a1ed6539 chain=BTC, network=regtest
info: Sync  chain=BCH, network=regtest, height=65
error: Error syncing BTC regtest reorg
info: Sync  chain=BTC, network=regtest, height=18
info: Syncing 84 blocks for BTC regtest
info: Sync  chain=BTC, network=regtest, height=19
info: Sync  chain=LTC, network=regtest, height=64
info: Resetting tip to 522995131b39314502296259ce71c371409e2aa4d636e86bc2e4a08db61460ff chain=BTC, network=regtest
info: Sync  chain=BTC, network=regtest, height=19
info: Resetting tip to 6bc2591c9219dc93645c8b1c6330738321c2de05996c8e25db5b2dfb45ca2bd9 chain=BTC, network=regtest
info: Resetting tip to 6bc2591c9219dc93645c8b1c6330738321c2de05996c8e25db5b2dfb45ca2bd9 chain=BTC, network=regtest
info: Resetting tip to 6bc2591c9219dc93645c8b1c6330738321c2de05996c8e25db5b2dfb45ca2bd9 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
error: Error syncing BTC regtest reorg
error: Error syncing BTC regtest reorg
error: Error syncing BTC regtest reorg
info: Syncing 86 blocks for BTC regtest
info: Syncing 86 blocks for BTC regtest
info: Syncing 86 blocks for BTC regtest
info: Syncing 86 blocks for BTC regtest
info: Sync  chain=BCH, network=regtest, height=67
info: Sync  chain=BTC, network=regtest, height=16
info: Sync  chain=BTC, network=regtest, height=16
info: Sync  chain=BTC, network=regtest, height=16
info: Sync  chain=BTC, network=regtest, height=16
info: Sync  chain=LTC, network=regtest, height=66
info: Sync  chain=BCH, network=regtest, height=69
info: Sync  chain=BTC, network=regtest, height=18
info: Sync  chain=BTC, network=regtest, height=18
info: Sync  chain=BTC, network=regtest, height=18
info: Sync  chain=LTC, network=regtest, height=68
info: Sync  chain=BTC, network=regtest, height=18
info: Sync  chain=BCH, network=regtest, height=71
info: Sync  chain=BTC, network=regtest, height=20
info: Sync  chain=BTC, network=regtest, height=20
info: Sync  chain=BTC, network=regtest, height=20
info: Sync  chain=LTC, network=regtest, height=70
info: Sync  chain=BTC, network=regtest, height=21
info: Sync  chain=BCH, network=regtest, height=73
info: Sync  chain=BTC, network=regtest, height=22
info: Sync  chain=BTC, network=regtest, height=22
info: Sync  chain=BTC, network=regtest, height=22
info: Sync  chain=LTC, network=regtest, height=72
info: Sync  chain=BTC, network=regtest, height=23
info: Sync  chain=BTC, network=regtest, height=23
info: Sync  chain=BTC, network=regtest, height=23
info: Sync  chain=BTC, network=regtest, height=23
info: Sync  chain=BCH, network=regtest, height=74
info: Sync  chain=LTC, network=regtest, height=73
info: Sync  chain=BTC, network=regtest, height=25
info: Sync  chain=BTC, network=regtest, height=25
info: Sync  chain=BTC, network=regtest, height=25
info: Sync  chain=BTC, network=regtest, height=25
info: Sync  chain=BCH, network=regtest, height=76
info: Sync  chain=LTC, network=regtest, height=75
info: Sync  chain=BTC, network=regtest, height=27
info: Sync  chain=BTC, network=regtest, height=27
info: Sync  chain=BTC, network=regtest, height=27
info: Sync  chain=BCH, network=regtest, height=78
info: Sync  chain=BTC, network=regtest, height=27
info: Sync  chain=LTC, network=regtest, height=78
info: Sync  chain=BCH, network=regtest, height=82
info: Sync  chain=BTC, network=regtest, height=29
info: Sync  chain=LTC, network=regtest, height=81
info: Sync  chain=BTC, network=regtest, height=29
info: Sync  chain=BTC, network=regtest, height=29
info: Sync  chain=BTC, network=regtest, height=29
info: Sync  chain=BCH, network=regtest, height=84
info: Sync  chain=BTC, network=regtest, height=31
info: Sync  chain=BTC, network=regtest, height=31
info: Sync  chain=BTC, network=regtest, height=31
info: Sync  chain=LTC, network=regtest, height=83
info: Sync  chain=BTC, network=regtest, height=31
info: Sync  chain=BCH, network=regtest, height=86
info: Sync  chain=BTC, network=regtest, height=33
info: Sync  chain=BTC, network=regtest, height=33
info: Sync  chain=BTC, network=regtest, height=33
info: Sync  chain=BTC, network=regtest, height=33
info: Sync  chain=LTC, network=regtest, height=85
info: Sync  chain=BCH, network=regtest, height=88
info: Sync  chain=BTC, network=regtest, height=35
info: Sync  chain=BTC, network=regtest, height=35
info: Sync  chain=BTC, network=regtest, height=35
info: Sync  chain=BTC, network=regtest, height=35
info: Sync  chain=LTC, network=regtest, height=87
info: Sync  chain=BTC, network=regtest, height=37
info: Sync  chain=BTC, network=regtest, height=37
info: Sync  chain=BTC, network=regtest, height=37
info: Sync  chain=BCH, network=regtest, height=90
info: Sync  chain=BTC, network=regtest, height=37
info: Sync  chain=LTC, network=regtest, height=89
info: Sync  chain=BTC, network=regtest, height=39
info: Sync  chain=BTC, network=regtest, height=39
info: Sync  chain=BTC, network=regtest, height=39
info: Sync  chain=BCH, network=regtest, height=92
info: Sync  chain=BTC, network=regtest, height=39
info: Sync  chain=LTC, network=regtest, height=91
info: Sync  chain=BCH, network=regtest, height=94
info: Sync  chain=BTC, network=regtest, height=41
info: Sync  chain=BTC, network=regtest, height=41
info: Sync  chain=BTC, network=regtest, height=41
info: Sync  chain=LTC, network=regtest, height=93
info: Sync  chain=BTC, network=regtest, height=41
info: Sync  chain=BCH, network=regtest, height=96
info: Sync  chain=BTC, network=regtest, height=44
info: Sync  chain=BTC, network=regtest, height=44
info: Sync  chain=BTC, network=regtest, height=44
info: Sync  chain=LTC, network=regtest, height=96
info: Sync  chain=BTC, network=regtest, height=44
info: Sync  chain=BCH, network=regtest, height=99
info: Sync  chain=BTC, network=regtest, height=47
info: Sync  chain=BTC, network=regtest, height=47
info: Sync  chain=BTC, network=regtest, height=47
info: Sync  chain=BTC, network=regtest, height=47
info: Sync  chain=LTC, network=regtest, height=100
info: Syncing 0 blocks for BCH regtest
info: BCH:regtest up to date.
info: Syncing 0 blocks for LTC regtest
info: LTC:regtest up to date.
info: Sync  chain=BTC, network=regtest, height=51
info: Sync  chain=BTC, network=regtest, height=51
info: Sync  chain=BTC, network=regtest, height=51
info: Sync  chain=BTC, network=regtest, height=51
info: Sync  chain=BTC, network=regtest, height=56
info: Sync  chain=BTC, network=regtest, height=56
info: Sync  chain=BTC, network=regtest, height=56
info: Sync  chain=BTC, network=regtest, height=56
info: Sync  chain=BTC, network=regtest, height=61
info: Sync  chain=BTC, network=regtest, height=61
info: Sync  chain=BTC, network=regtest, height=61
info: Sync  chain=BTC, network=regtest, height=61
info: Sync  chain=BTC, network=regtest, height=64
info: Sync  chain=BTC, network=regtest, height=64
info: Sync  chain=BTC, network=regtest, height=64
info: Sync  chain=BTC, network=regtest, height=64
info: Sync  chain=BTC, network=regtest, height=69
info: Sync  chain=BTC, network=regtest, height=69
info: Sync  chain=BTC, network=regtest, height=69
info: Sync  chain=BTC, network=regtest, height=69
info: Sync  chain=BTC, network=regtest, height=73
info: Sync  chain=BTC, network=regtest, height=73
info: Sync  chain=BTC, network=regtest, height=73
info: Sync  chain=BTC, network=regtest, height=73
info: Sync  chain=BTC, network=regtest, height=78
info: Sync  chain=BTC, network=regtest, height=78
info: Sync  chain=BTC, network=regtest, height=78
info: Sync  chain=BTC, network=regtest, height=78
info: Sync  chain=BTC, network=regtest, height=82
info: Sync  chain=BTC, network=regtest, height=82
info: Sync  chain=BTC, network=regtest, height=82
info: Sync  chain=BTC, network=regtest, height=82
info: Sync  chain=BTC, network=regtest, height=87
info: Sync  chain=BTC, network=regtest, height=87
info: Sync  chain=BTC, network=regtest, height=87
info: Sync  chain=BTC, network=regtest, height=87
info: Sync  chain=BTC, network=regtest, height=93
info: Sync  chain=BTC, network=regtest, height=93
info: Sync  chain=BTC, network=regtest, height=93
info: Sync  chain=BTC, network=regtest, height=93
info: Sync  chain=BTC, network=regtest, height=98
info: Sync  chain=BTC, network=regtest, height=98
info: Sync  chain=BTC, network=regtest, height=99
info: Sync  chain=BTC, network=regtest, height=99
info: Syncing 6 blocks for BTC regtest
info: Syncing 6 blocks for BTC regtest
info: Syncing 6 blocks for BTC regtest
info: Syncing 6 blocks for BTC regtest
info: Sync  chain=BTC, network=regtest, height=102
info: Sync  chain=BTC, network=regtest, height=102
info: Sync  chain=BTC, network=regtest, height=102
info: Sync  chain=BTC, network=regtest, height=102
info: Sync  chain=BTC, network=regtest, height=105
info: Sync  chain=BTC, network=regtest, height=105
info: Sync  chain=BTC, network=regtest, height=105
info: Sync  chain=BTC, network=regtest, height=106
info: Syncing 0 blocks for BTC regtest
info: BTC:regtest up to date.
info: Syncing 0 blocks for BTC regtest
info: BTC:regtest up to date.
info: Added block 1e8f36fd7f02b48a086c1f1a0affdd4fe21ccfe30944a48de733986046af9810 chain=BTC, network=regtest
info: Added block 1e8f36fd7f02b48a086c1f1a0affdd4fe21ccfe30944a48de733986046af9810 chain=BTC, network=regtest
info: Syncing 0 blocks for BTC regtest
info: BTC:regtest up to date.
info: Syncing 0 blocks for BTC regtest
info: BTC:regtest up to date.
```

**Comment by micahriggan** [comment]
Ahhh! I know what this is, it's restarting sync a bunch of times in parallel, since the events are all getting triggered at the same time.

The on('peerblock') should have await this.sync(), not return.... that's a typo.

**Comment by micahriggan** [comment]
Also, when calling sync, we should only run the logic if this.syncing was false when the function was called. Else, we'll have two going at the same time

**Comment by osagga** [comment]
Although it makes sense, I tried the following:


I changed the default `this.syncing` to `false` (I'll explain later why)
https://github.com/bitpay/bitcore/blob/816c8e8619dc74d08033ded673b7213c6e59c3a6/packages/bitcore-node/src/services/p2p.ts#L32

I changed to `await this.sync()` as you mentioned above
https://github.com/bitpay/bitcore/blob/816c8e8619dc74d08033ded673b7213c6e59c3a6/packages/bitcore-node/src/services/p2p.ts#L105

I added the check on `sync()` to only run if `this.syncing` is false as follows
```
if (this.syncing) { return; }
```
Because of this check I needed to force this.syncing to start as `false`, because otherwise `sync` will never do anything (since this check will always be triggered).


After that I ran the node and I generated `101` blocks (on BTC regtest, using bitcoin-core `0.16.2`)

and this is my bitcore-node output log:
```
info: API server started on port 3000
info: Connected to peer 127.0.0.1 chain=BTC, network=regtest
info: Connected to peer 127.0.0.1 chain=BCH, network=regtest
info: Connected to peer 127.0.0.1 chain=LTC, network=regtest
info: Syncing 0 blocks for BTC regtest
info: BTC:regtest up to date.
info: Syncing 0 blocks for BCH regtest
info: BCH:regtest up to date.
info: Syncing 0 blocks for LTC regtest
info: LTC:regtest up to date.
info: Added block 0267077285f1ba665d0371b254c6a9e0ad2b74704942c0eac2c526e293c452e6 chain=BTC, network=regtest
info: Resetting tip to 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
info: Syncing 25 blocks for BTC regtest
info: Resetting tip to 507df9912b47f63217f93bbdc78cdae0e1861a7d96450f30f482e7f83cf9c463 chain=BTC, network=regtest
error: Error syncing BTC regtest reorg
```

Also calling `[node-ip]:3000/api/BTC/regtest/block/tip` returns the following:
```
{
    "chain": "BTC",
    "network": "regtest",
    "hash": "507df9912b47f63217f93bbdc78cdae0e1861a7d96450f30f482e7f83cf9c463",
    "height": 1,
    "version": 536870912,
    "size": 226,
    "merkleRoot": "3f022389fd8d8ebc464f97fb8806c04bbe3e4be825fb07803424cc4bb988f89b",
    "time": "2018-08-14T14:02:38.000Z",
    "timeNormalized": "2018-08-14T14:02:38.000Z",
    "nonce": 1,
    "bits": 545259519,
    "previousBlockHash": "1f4cebe7ecb27effd3ecd650eb1de60501a9f038e3007e680d7fb503db5fed41",
    "nextBlockHash": "1705fad1ba82bb6f63f9066a2763c287e59655b8088400c7ad493fd3e5f7e068",
    "reward": 5000000000,
    "transactionCount": 1
}
```

Notice that the `height` is `1` rather than `25` (as shown in the log), also the blockhash provided above matches the forth block on the bitcoin-node
```
$ ./bitcoin-0.16.2/bin/bitcoin-cli -datadir=./data/ getblock 507df9912b47f63217f93bbdc78cdae0e1861a7d96450f30f482e7f83cf9c463
{
  "hash": "507df9912b47f63217f93bbdc78cdae0e1861a7d96450f30f482e7f83cf9c463",
  "confirmations": 98,
  "strippedsize": 226,
  "size": 262,
  "weight": 940,
  "height": 4,
  "version": 536870912,
  "versionHex": "20000000",
  "merkleroot": "3f022389fd8d8ebc464f97fb8806c04bbe3e4be825fb07803424cc4bb988f89b",
  "tx": [
    "3f022389fd8d8ebc464f97fb8806c04bbe3e4be825fb07803424cc4bb988f89b"
  ],
  "time": 1534255358,
  "mediantime": 1534255357,
  "nonce": 1,
  "bits": "207fffff",
  "difficulty": 4.656542373906925e-10,
  "chainwork": "000000000000000000000000000000000000000000000000000000000000000a",
  "nTx": 1,
  "previousblockhash": "1f4cebe7ecb27effd3ecd650eb1de60501a9f038e3007e680d7fb503db5fed41",
  "nextblockhash": "1705fad1ba82bb6f63f9066a2763c287e59655b8088400c7ad493fd3e5f7e068"
}
```

It seems that the `bitcoin-core` node doesn't notify the `bitcore-node` of the `101` blocks at once, instead, it'll notify it of partial updates as soon as it generates the blocks.

So I think by awaiting on `this.sync()`, we dont not trigger a new sync call, therefore, not updating to the current latest block received, since the current sync call (we await on) is just updating to the previous latest block.

So maybe we need some sort on wait and then trigger logic on `this.sync`. Let me know what do you think

**Comment by osagga** [comment]
Are you going to merge it or should I test it on your branch?

**Comment by osagga** [comment]
Update: This still doesn't solve the problem completely. When generating blocks really fast, the blockExplorer seems to drop some of them. 

Probably caused by the `reorg` event that gets triggered. The fix #1673 will work if we generate block slowly, but stress testing the blockExplorer causes some blocks to be missed.

**Comment by osagga** [comment]
@micahriggan I think this problem is causing #1676 to happen, I was able to prevent #1676 by simply putting a lock on the RPC generate command in a multi threaded application. Do you know what could still be causing `generate` to make the node act weirdly?

**Comment by osagga** [comment]
@micahriggan 

I did more digging and it seems that some blocks get dropped after being added to the blockchain. For example, I will end up with a blockchain that has the correct height as what `bitcoind` reports, but it would have some holes in it (missing blocks). So it must be the case that the block was added, and another block was added after that one (since the block height is correct), but then that block was removed for some reason.

Given the code in the Block model and p2p, a block would only get removed in the case of a `reorg` event (the tip will be dropped), so I suspect that this problem has to do with the reorg event that gets triggered in the p2p `peerblock` handler, and the `sync` function having some race condition such that it doesn't re-sync some blocks.

**Comment by osagga** [comment]
@micahriggan Hey, any updates on this? It's a really bad bug that's stopping me from using `v8`, let me know if you have any idea about what could cause it.

**Comment by micahriggan** [comment]
@osagga I will look at this now for a little bit, but right now our main goal is getting this to be stable with BWS and getting insight to a usable point, so that's what I work on when I'm at the office

**Comment by micahriggan** [comment]
@osagga can you see if #1729 solves this for you? I'm able to generate 1000 at a time now and it works. I can also completely delete regtest, and then re-generate a new chain, and it slowly winds back the old chain and then re-syncs the new one

**Comment by osagga** [comment]
@micahriggan After testing out the fix in #1729, it turns out the the problem is not fully fixed. 

In your fix, `processBlock` was only being locked in the blockHandler, but it doesn't prevent the case where processBlock is being accessed by `this.sync()` and the block handler at the same time.

https://github.com/bitpay/bitcore/blob/9772e42a0c2ce0c483560e4fddcbbc2473563cb0/packages/bitcore-node/src/services/p2p.ts#L101-L103

You can see that threads wait for the lock after passing the syncing check, which would result in one thread executing `this.sync()` and another thread doing `processBlock`. This causes the chain state to be undefined since we would be adding and potentially removing blocks at the same time.

My fix (88f14ec9c48bdd0909967ebe013b029639320d44) to this is to lock `processBlock` internally the same way `this.sync()` gets locked. This way we can guarantee that only one processBlock is running at any point within `p2p`. 

Let me know what you think

**Comment by micahriggan** [comment]
My only concern with yours is that it just returns if it's already adding one. I have one more idea, I'm going to try calling sync instead of processing blocks in the event handler

**Comment by micahriggan** [comment]
https://github.com/bitpay/bitcore/pull/1739/files

That appears to be working
